version: '3.8'
services:
  dynamodb-local:
    container_name: 'dynamodb-local'
    image: 'amazon/dynamodb-local:latest'
    command: '-Xms256m -Xmx4g -jar DynamoDBLocal.jar -sharedDb -dbPath /dynamodb_data'
    volumes:
      - ./dynamodb-local:/dynamodb_data
    ports:
      - '8000:8000'
  sl-manager-api:
    container_name: 'sl-manager-api'
    build: '../sl-manager-nest-api/'
    volumes:
      - ../sl-manager-nest-api/.build:/sl-manager-api/.build
      - ../sl-manager-nest-api/src:/sl-manager-api/src
      - ../sl-manager-nest-api/test:/sl-manager-api/test
      - ../sl-manager-nest-api/.env:/sl-manager-api/.env
      - ../sl-manager-nest-api/serverless.yml:/sl-manager-api/serverless.yml
    command: sls offline start
    ports:
      - '5002:5002'
      - '5011:5011'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  default:
    name: sl-manager-local_default
