version: '3.8'
services:
  sl-manager-db:
    image: postgres:14.1-alpine
    container_name: sl-manager-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:54320'
    volumes:
      - sl-manager-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  # sl-manager-api:
  #   container_name: 'sl-manager-api'
  #   build: '../sl-manager-nest-api/'
  #   volumes:
  #     - ../sl-manager-nest-api/.build:/sl-manager-api/.build
  #     - ../sl-manager-nest-api/src:/sl-manager-api/src
  #     - ../sl-manager-nest-api/test:/sl-manager-api/test
  #     - ../sl-manager-nest-api/.env:/sl-manager-api/.env
  #     - ../sl-manager-nest-api/serverless.yml:/sl-manager-api/serverless.yml
  #   command: sls offline start --prefix 'sl-manager-api' --noPrependStageInUrl
  #   ports:
  #     - '5002:5002'
  #     - '5011:5011'
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
volumes:
  sl-manager-db:
  pgadmin-data:
networks:
  default:
    name: sl-manager-local_default
